var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);var Point=function(a,b){this._x=a;this._y=b};$jscomp.global.Object.defineProperties(Point.prototype,{x:{configurable:!0,enumerable:!0,get:function(){return this._x}},y:{configurable:!0,enumerable:!0,get:function(){return this._y}}});
var Bullet=function(a,b,c,d,e){this._sprite=a;this._position=b;this._speed=c;this._spriteName=d;this._spritePath=e};
$jscomp.global.Object.defineProperties(Bullet.prototype,{sprite:{configurable:!0,enumerable:!0,get:function(){return this._sprite},set:function(a){this._sprite=a}},position:{configurable:!0,enumerable:!0,get:function(){return this._position},set:function(a){this._position=a}},speed:{configurable:!0,enumerable:!0,get:function(){return this._speed},set:function(a){this._speed=a}},spriteName:{configurable:!0,enumerable:!0,get:function(){return this._spriteName},set:function(a){this._spriteName=a}},spritePath:{configurable:!0,
enumerable:!0,get:function(){return this._spritePath},set:function(a){this._spritePath=a}}});var Missile=function(a,b,c,d,e,f,g,h){this._sprite=a;this._position=b;this._speed=c;this._rotationSpeed=d;this._spriteName=e;this._spritePath=f;this._sightSprite=g;this._emitter=h};
$jscomp.global.Object.defineProperties(Missile.prototype,{sprite:{configurable:!0,enumerable:!0,get:function(){return this._sprite},set:function(a){this._sprite=a}},position:{configurable:!0,enumerable:!0,get:function(){return this._position},set:function(a){this._position=a}},speed:{configurable:!0,enumerable:!0,get:function(){return this._speed},set:function(a){this._speed=a}},rotationSpeed:{configurable:!0,enumerable:!0,get:function(){return this._rotationSpeed},set:function(a){this._rotationSpeed=
a}},spriteName:{configurable:!0,enumerable:!0,get:function(){return this._spriteName},set:function(a){this._spriteName=a}},spritePath:{configurable:!0,enumerable:!0,get:function(){return this._spritePath},set:function(a){this._spritePath=a}},sightSprite:{configurable:!0,enumerable:!0,get:function(){return this._sightSprite},set:function(a){this._sightSprite=a}},emitter:{configurable:!0,enumerable:!0,get:function(){return this._emitter},set:function(a){this._emitter=a}}});
var Airplane=function(a,b,c,d,e,f,g,h,k){this._sprite=a;this._anim=b;this._shadow=c;this._position=d;this._speed=e;this._rotationSpeed=f;this._spriteName=g;this._framesQuantity=h;this._spritePath=k};
$jscomp.global.Object.defineProperties(Airplane.prototype,{sprite:{configurable:!0,enumerable:!0,get:function(){return this._sprite},set:function(a){this._sprite=a}},anim:{configurable:!0,enumerable:!0,get:function(){return this._anim},set:function(a){this._anim=a}},shadow:{configurable:!0,enumerable:!0,get:function(){return this._shadow},set:function(a){this._shadow=a}},position:{configurable:!0,enumerable:!0,get:function(){return this._position},set:function(a){this._position=a}},speed:{configurable:!0,
enumerable:!0,get:function(){return this._speed},set:function(a){this._speed=a}},rotationSpeed:{configurable:!0,enumerable:!0,get:function(){return this._rotationSpeed},set:function(a){this._rotationSpeed=a}},spriteName:{configurable:!0,enumerable:!0,get:function(){return this._spriteName},set:function(a){this._spriteName=a}},framesQuantity:{configurable:!0,enumerable:!0,get:function(){return this._framesQuantity},set:function(a){this._framesQuantity=a}},spritePath:{configurable:!0,enumerable:!0,
get:function(){return this._spritePath},set:function(a){this._spritePath=a}}});
