var IDE_HOOK=!1,VERSION="2.6.2",WORLD_SIZE=32768,SCREEN_WIDTH=window.screen.availWidth,SCREEN_HEIGHT=window.screen.height,OFFSET=new Phaser.Point(75,75),time=0,delta=0,last=0,lastTime=0,deltaInterval=0,DELTA_LIMIT=.12,AIRPLANE_SPEED=400,ROTATION_SPEED=1,MISSILE_ROTATION_SPEED=1.5,BULLET_SPEED=800,MISSILE_SPEED=650,SHOOT_DISTANCE=45,BULLET_FIRE_RATE=300,MISSILE_FIRE_RATE=500,game=new Phaser.Game(SCREEN_WIDTH,SCREEN_HEIGHT,Phaser.CANVAS,"phaser-example",{preload:preload,create:create,update:update,
render:render}),planeLayer,shadowLayer,isAlive=!0,airplane=new Airplane(null,null,null,new Point(15E3,15E3),AIRPLANE_SPEED,ROTATION_SPEED,"airplane",7,"assets/sprites/planes/EPF-23/EPF-23.png"),enemiesArray=[],bulletsArray=[],missilesArray=[],nextFire=0,sight,sightSprite,enemiesAmount=32,airplaneSpeedDelta=AIRPLANE_SPEED+5,rotationSpeedDelta=ROTATION_SPEED-.1;
for(i=0;i<enemiesAmount;i++){var enemyPlane=new Airplane(null,null,null,new Point(16E3,16E3),airplaneSpeedDelta,rotationSpeedDelta,"enemyPlane_01",9,"assets/sprites/planes/AJ-44/AJ-44_beige.png");enemiesArray.push(enemyPlane);airplaneSpeedDelta+=5;rotationSpeedDelta-=.02}
function preload(){game.load.image("background","assets/tests/debug-grid-1920x1920.png");game.load.spritesheet(airplane.spriteName,airplane.spritePath,71,43,airplane.framesQuantity);game.load.spritesheet("explosion","assets/sprites/explosion_01_17F.png",99,99);game.load.image("bullet","assets/sprites/weapons/bullet.png",11,11);game.load.image("missile_01","assets/sprites/weapons/missile_03.png",30,11);game.load.image("stele","assets/particles/stele_gold.png");for(i=0;i<enemiesArray.length;i++)game.load.spritesheet(enemiesArray[i].spriteName,
enemiesArray[i].spritePath,74,75,enemiesArray[i].framesQuantity)}
function create(){shadowLayer=game.add.group();planeLayer=game.add.group();game.scale.scaleMode=Phaser.ScaleManager.SHOW_ALL;game.scale.fullScreenTarget=game.canvas;document.documentElement.style.overflow="hidden";game.add.tileSprite(0,0,WORLD_SIZE,WORLD_SIZE,"background");game.world.setBounds(0,0,WORLD_SIZE,WORLD_SIZE);initializeAirplane(airplane,!0);for(i=0;i<enemiesArray.length;i++)initializeAirplane(enemiesArray[i],!1);console.log("airplane.spritePath:"+airplane.spritePath);console.log("game.camera.view:"+
Object.getOwnPropertyNames(game.camera.view))}
function initializeAirplane(a,b){console.log("initializeAirplane() sprite:"+a.spriteName);a.sprite=game.add.sprite(a.position.x,a.position.y,a.spriteName,5);a.sprite.scale.set(1);a.sprite.smoothed=!1;a.anim=a.sprite.animations.add(a.spriteName);a.sprite.anchor.setTo(.5,.5);a.sprite.z=20;game.physics.enable(a.sprite,Phaser.Physics.ARCADE);a.shadow=game.add.sprite(a.position.x+OFFSET.x,a.position.y+OFFSET.y,a.spriteName,5);a.shadow.scale.set(.4);a.shadow.anchor.setTo(.5,.5);a.shadow.tint=0;a.shadow.alpha=
.6;a.shadow.z=10;game.physics.enable(a.shadow,Phaser.Physics.ARCADE);game.world.bringToTop(a.sprite);b?game.camera.follow(a.sprite):(a.sprite.inputEnabled=!0,a.sprite.events.onInputOver.add(highlight,game),a.sprite.events.onInputOut.add(out,game));a.sprite.frame=getFrameCenter(a.framesQuantity)}
function initializeBullet(a){a.sprite=game.add.sprite(a.position.x,a.position.y,a.spriteName,5);a.sprite.scale.set(1);a.sprite.smoothed=!1;a.anim=a.sprite.animations.add(a.spriteName);a.sprite.anchor.setTo(.5,.5);a.sprite.z=20;game.physics.enable(a.sprite,Phaser.Physics.ARCADE);game.world.bringToTop(a.sprite)}
function initializeMissile(a){a.sprite=game.add.sprite(a.position.x,a.position.y,a.spriteName,5);a.sprite.scale.set(1);a.sprite.smoothed=!1;a.anim=a.sprite.animations.add(a.spriteName);a.sprite.anchor.setTo(.5,.5);a.sprite.z=20;game.physics.enable(a.sprite,Phaser.Physics.ARCADE);game.world.bringToTop(a.sprite);a.emitter.width=3;a.emitter.makeParticles("stele");a.emitter.minParticleSpeed.set(0,0);a.emitter.maxParticleSpeed.set(0,0);a.emitter.setRotation(-180,180);a.emitter.setScale(.05,.15,.05,.15);
a.emitter.gravity=0;a.emitter.start(!1,500,20)}function checkOverlap(a,b){a=getReducedBound(a);b=getReducedBound(b);return Phaser.Rectangle.intersects(a,b)}function getReducedBound(a){var b=(a.width+a.height)/2/100*85;return new Phaser.Rectangle(a.getBounds().x,a.getBounds().y,b,b)}
function explode(a){a.sprite.loadTexture("explosion",0);a.sprite.animations.add("explosion",[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],24,!1,!0);a.sprite.animations.currentAnim.onComplete.add(function(){},this);a.shadow.visible=!1;a.sprite.play("explosion",24,!1,!0)}
function update(){game.physics.arcade.velocityFromAngle(airplane.sprite.angle,airplane.speed,airplane.sprite.body.velocity);game.physics.arcade.velocityFromAngle(airplane.shadow.angle,airplane.speed,airplane.shadow.body.velocity);generateDelta();var a=degrees(game.physics.arcade.angleToPointer(airplane.sprite));rotateObject(a,airplane,deltaInterval);enemyPlanesFollowUs();missileFollowPlanes();deltaInterval>DELTA_LIMIT&&(deltaInterval=0);checkCollision();game.input.activePointer.leftButton.isDown&&
fire();game.input.activePointer.rightButton.isDown&&throwMissile(getEnemyPlaneBySightSprite());void 0!=sightSprite&&(sight.position=new Point(sightSprite.position.x,sightSprite.position.y));removeNonVisibleBullets()}
function enemyPlanesFollowUs(){for(i=0;i<enemiesArray.length;i++){game.physics.arcade.velocityFromAngle(enemiesArray[i].sprite.angle,enemiesArray[i].speed,enemiesArray[i].sprite.body.velocity);game.physics.arcade.velocityFromAngle(enemiesArray[i].shadow.angle,enemiesArray[i].speed,enemiesArray[i].shadow.body.velocity);var a=degrees(game.physics.arcade.angleBetween(enemiesArray[i].sprite,airplane.sprite));rotateObject(a,enemiesArray[i],deltaInterval)}}
function missileFollowPlanes(){for(i=0;i<missilesArray.length;i++){game.physics.arcade.velocityFromAngle(missilesArray[i].sprite.angle,missilesArray[i].speed,missilesArray[i].sprite.body.velocity);var a=degrees(game.physics.arcade.angleBetween(missilesArray[i].sprite,missilesArray[i].sightSprite));rotateObject(a,missilesArray[i],deltaInterval);missilesArray[i].emitter.x=missilesArray[i].sprite.position.x+15*Math.cos(missilesArray[i].sprite.rotation+Math.PI);missilesArray[i].emitter.y=missilesArray[i].sprite.position.y+
15*Math.sin(missilesArray[i].sprite.rotation+Math.PI)}}function getEnemyPlaneBySightSprite(){for(i=0;i<enemiesArray.length;i++)if(enemiesArray[i].sprite==sightSprite){var a=enemiesArray[i].sprite;break}return a}
function checkCollision(){for(i=0;i<enemiesArray.length;i++){for(j=0;j<bulletsArray.length;j++)0<enemiesArray.length&&void 0!=enemiesArray[i]&&checkOverlap(enemiesArray[i].sprite,bulletsArray[j].sprite)&&(console.log("enemyPlane["+i+"] "+enemiesArray[i].spriteName+": ELIMINATED BY A BULLET"),bulletsArray[j].sprite.visible=!1,explode(enemiesArray[i]),remove(bulletsArray,bulletsArray[i]),remove(enemiesArray,enemiesArray[i]));for(j=0;j<missilesArray.length;j++)0<enemiesArray.length&&void 0!=enemiesArray[i]&&
void 0!=missilesArray[j]&&checkOverlap(enemiesArray[i].sprite,missilesArray[j].sprite)&&(console.log("enemyPlane["+i+"] "+enemiesArray[i].spriteName+": ELIMINATED BY A MISSILE"),missilesArray[j].sprite.visible=!1,explode(enemiesArray[i]),missilesArray[j].emitter.on=!1,remove(missilesArray,missilesArray[j]),remove(enemiesArray,enemiesArray[i]));0<enemiesArray.length&&void 0!=enemiesArray[i]&&checkOverlap(airplane.sprite,enemiesArray[i].sprite)&&isAlive&&(isAlive=!1,console.log("enemyPlane["+i+"] "+
enemiesArray[i].spriteName+": ELIMINATED BY CRASH"),console.log("*** CRASHED ***"),explode(airplane),explode(enemiesArray[i]),remove(enemiesArray,enemiesArray[i]))}}
function fire(){if(game.time.now>nextFire){nextFire=game.time.now+BULLET_FIRE_RATE;var a=new Point(airplane.sprite.x+Math.cos(airplane.sprite.rotation)*SHOOT_DISTANCE,airplane.sprite.y+Math.sin(airplane.sprite.rotation)*SHOOT_DISTANCE);a=new Bullet(null,a,BULLET_SPEED,"bullet","assets/sprites/weapons/bullet.png");initializeBullet(a);a.sprite.rotation=airplane.sprite.rotation;game.physics.arcade.velocityFromAngle(airplane.sprite.angle,a.speed,a.sprite.body.velocity);bulletsArray.push(a)}}
function throwMissile(a){if(game.time.now>nextFire&&void 0!=a){nextFire=game.time.now+MISSILE_FIRE_RATE;var b=airplane.sprite.x+Math.cos(airplane.sprite.rotation)*SHOOT_DISTANCE,c=airplane.sprite.y+Math.sin(airplane.sprite.rotation)*SHOOT_DISTANCE,e=new Point(b,c);b=game.add.emitter(b,c,100);a=new Missile(null,e,MISSILE_SPEED,MISSILE_ROTATION_SPEED,"missile_01","assets/sprites/weapons/missile_01.png",a,b);initializeMissile(a);a.sprite.rotation=airplane.sprite.rotation;game.physics.arcade.velocityFromAngle(airplane.sprite.angle,
a.speed,a.sprite.body.velocity);missilesArray.push(a)}}function removeNonVisibleBullets(){for(j=0;j<bulletsArray.length;j++){var a=new Phaser.Rectangle(game.camera.view.x,game.camera.view.y,game.camera.view.width,game.camera.view.height),b=new Phaser.Rectangle(bulletsArray[j].sprite.x,bulletsArray[j].sprite.y,bulletsArray[j].sprite.width,bulletsArray[j].sprite.height);0==Phaser.Rectangle.intersects(a,b)&&remove(bulletsArray,bulletsArray[j])}}function getRoute(a){}
function degrees(a){return 180+180/Math.PI*a}
function render(){game.debug.spriteInfo(airplane.sprite,32,32);game.debug.cameraInfo(game.camera,32,128);game.debug.spriteCoords(airplane.sprite,32,500);game.debug.text("airplane.sprite.getBounds().x:"+airplane.sprite.getBounds().x,32,640);game.debug.text("airplane.sprite.getBounds().y:"+airplane.sprite.getBounds().y,32,660);game.debug.text("airplane.sprite.getBounds().width:"+airplane.sprite.getBounds().width,32,680);game.debug.text("airplane.sprite.getBounds().height:"+airplane.sprite.getBounds().height,
32,700);game.debug.text("airplane.sprite.angle:"+degrees(airplane.sprite.rotation),32,720);game.debug.text("bulletsArray.length:"+bulletsArray.length,32,760);game.debug.text("enemiesArray.length:"+enemiesArray.length,32,780);game.debug.text("game.camera.view: width:"+game.camera.view.width+" height:"+game.camera.view.height+" x"+game.camera.view.x+" y:"+game.camera.view.y,32,800);if(0<missilesArray.length){var a=840;for(j=0;j<missilesArray.length;j++)game.debug.text("missilesArray["+j+"].position x:"+
missilesArray[j].sprite.position.x+"y:"+missilesArray[j].sprite.position.y+" missilesArray[j].emitter:"+missilesArray[j].emitter,32,a),a+=20}}function generateDelta(){var a=Date.now();time+=(a-last)/1E3;delta=time-lastTime;lastTime=time;last=a;deltaInterval+=delta}
function rotateObject(a,b,c){if(void 0!=b){c=degrees(b.sprite.rotation);var e=Math.abs(c-a),d=Math.PI/180*360;360<c&&(b.rotation-=d,b.shadow.rotation-=d);0>c&&(b.rotation+=d,b.shadow.rotation+=d);1<e?180>c?180>a?a<c?turnLeft(b):turnRight(b):a>c+180?turnLeft(b):turnRight(b):180<a?a<c?turnLeft(b):turnRight(b):a>c-180?turnLeft(b):turnRight(b):deltaInterval>DELTA_LIMIT&&(b.anim.frame<getFrameCenter(b.framesQuantity)&&(b.anim.frame+=1),b.anim.frame>getFrameCenter(b.framesQuantity)&&--b.anim.frame)}}
function turnLeft(a){a.sprite.rotation-=a.rotationSpeed*delta;void 0!=a.shadow&&(a.shadow.rotation-=a.rotationSpeed*delta);deltaInterval>DELTA_LIMIT&&0<a.anim.frame&&--a.anim.frame}function turnRight(a){a.sprite.rotation+=a.rotationSpeed*delta;void 0!=a.shadow&&(a.shadow.rotation+=a.rotationSpeed*delta);deltaInterval>DELTA_LIMIT&&a.anim.frame<a.framesQuantity-1&&(a.anim.frame+=1)}function getFrameCenter(a){return(a-1)/2}function remove(a,b){b=a.indexOf(b);a.splice(b,1)}
function highlight(a){console.log("highlight()");drawSight(a)}function out(){console.log("out()");void 0!=sightSprite&&(sight.visible=!1,sight.destroy(),sightSprite=void 0)}
function drawSight(a){sightSprite=a;sight=game.add.graphics(a.position.x,a.position.y);sight.lineStyle(3,305478,2);sight.moveTo(0,-(a.width/1.5));sight.lineTo(0,-(a.width/2)+10);sight.moveTo(0,a.width/1.5);sight.lineTo(0,a.width/2-10);sight.moveTo(-(a.width/1.5),0);sight.lineTo(-(a.width/2)+10,0);sight.moveTo(a.width/1.5,0);sight.lineTo(a.width/2-10,0);sight.drawCircle(0,0,a.width+a.width/3)};
